# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: 'java -version'
  displayName: 'Find out Java Version'

- script: echo $(JAVA_HOME)
  displayName: Display Java Home

- task: CmdLine@2
  inputs:
    script: 'dir'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: 'InstantSpockExecutionRunner'
    
- task: CmdLine@2
  inputs:
    script: 'InstantSpockExecutionRunner.exe --environmentType=$(environmentType) --opkeyBaseUrl=$(opKeyBaseUrl) --sessionName=$(sessionName) --defaultPlugin=$(defaultPlugin) --build=$(build) --suitepath=$(suitePath) --browser=$(browser) --username=$(username) --apikey=$(apiKey) --project=$(project)'
    workingDirectory: '.\InstantSpockExecutionRunner\InstantSpockExecutionRunner\bin\Debug\netcoreapp3.1'
    

